// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import DirectoryController from "./directory_controller"
import ArchiveController from "./archive_controller"
application.register("hello", HelloController)
application.register("directory", DirectoryController)
application.register("archive", ArchiveController)
