require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Metrics/MethodLength:
  Max: 20

RSpec/MultipleMemoizedHelpers:
  Max: 15