require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Metrics/MethodLength:
  Max: 20

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/MultipleExpectations:
  Max: 15

RSpec/ExampleLength:
  Max: 20

RSpec/MessageSpies:
  Enabled: false

Style/HashSyntax:
  Enabled: false