inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'db/migrate/*'
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - '**/node_modules/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  Exclude:
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/validators/parent_validator_spec.rb'

Rails/InverseOf:
  Exclude:
    - 'app/models/storable.rb'

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'lib/tasks/*'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'db/schema.rb'
    - 'lib/tasks/*'

RSpec/ImplicitSubject:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/validators/parent_validator_spec.rb'