version: "3"
services:
  db:
    image: postgres:12-alpine
    restart: "no"
    ports:
      - "5431:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: "no"
    stdin_open: true
    tty: true
    volumes:
      - .:/icbh_rails_backend
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data: {}
