version: "3.7"
services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: rubydev_development
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.data:/var/lib/postgresql/data
  