version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: <%= ENV['DATABASE_USERNAME'] || 'root' %>
      POSTGRES_PASSWORD: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
      POSTGRES_HOST: localhost

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/apple-pie
    ports:
      - "3000:3000"
    depends_on:
      - db
