version: "3.9"

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build: .
    command: /bin/sh -c "bundle exec rails console"
    volumes:
      - .:/project
      - bundle:/.bundle
    ports:
      - 3000:3000
    depends_on:
      - database
    tty: true
    stdin_open: true
    environment:
      - PORT=3000
      - RAILS_ENV=development
      - DATABASE_HOST=database

  test:
    build: .
    command: /bin/sh -c "bundle exec rails db:drop && bundle exec rails db:create && bundle exec rails db:schema:load"
    volumes:
      - .:/project
      - bundle:/.bundle
    depends_on:
      - database
    tty: true
    stdin_open: true
    environment:
      - PORT=3000
      - RAILS_ENV=test
      - DATABASE_HOST=database

volumes:
  postgres:
  bundle:
