version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: bash -c "bundle && rails db:setup && rails s -b 0.0.0.0"
    volumes:
      - ./:/app
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
