version: '3.7'
services:
  db:
    image: 'postgres'
    ports:
      - 5432:5432
    volumes:
      - $HOME/.pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db