require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/subdirectories", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Directory. As you add validations to Directory, be sure to
  # adjust the attributes here as well.
  let(:directory_valid_attributes) {
    FactoryBot.attributes_for(:directory)
  }

  let(:valid_attributes) {
    FactoryBot.attributes_for(:subdirectory)
  }

  let(:invalid_attributes) {
    FactoryBot.attributes_for(:subdirectory, name: nil)
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # DirectoriesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      subdirectory = Subdirectory.create! valid_attributes
      get api_v1_directory_subdirectories_url(subdirectory.directory_id), headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      subdirectory = Subdirectory.create! valid_attributes
      get api_v1_directory_subdirectory_url(subdirectory.directory_id, subdirectory.id), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Subdirectory" do
        directory = Directory.create! directory_valid_attributes
        expect {
          post api_v1_directory_subdirectories_url(directory),
               params: { subdirectory: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Subdirectory, :count).by(1)
      end

      it "renders a JSON response with the new subdirectory" do
        directory = Directory.create! directory_valid_attributes
        post api_v1_directory_subdirectories_url(directory),
             params: { subdirectory: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Subdirectory" do
        directory = Directory.create! directory_valid_attributes
        expect {
          post api_v1_directory_subdirectories_url(directory),
               params: { subdirectory: invalid_attributes }, as: :json
        }.to change(Subdirectory, :count).by(0)
      end

      it "renders a JSON response with errors for the new subdirectory" do
        directory = Directory.create! directory_valid_attributes
        post api_v1_directory_subdirectories_url(directory),
             params: { subdirectory: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        FactoryBot.attributes_for(:subdirectory)
      }

      it "updates the requested subdirectory" do
        subdirectory = Subdirectory.create! valid_attributes
        patch api_v1_directory_subdirectory_url(subdirectory.directory_id, subdirectory.id),
              params: { subdirectory: new_attributes }, headers: valid_headers, as: :json
        subdirectory.reload
        expect(subdirectory.name).to eq(new_attributes[:name])
      end

      it "renders a JSON response with the subdirectory" do
        subdirectory = Subdirectory.create! valid_attributes
        patch api_v1_directory_subdirectory_url(subdirectory.directory_id, subdirectory.id),
              params: { subdirectory: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the subdirectory" do
        subdirectory = Subdirectory.create! valid_attributes
        patch api_v1_directory_subdirectory_url(subdirectory.directory_id, subdirectory.id),
              params: { subdirectory: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested subdirectory" do
      subdirectory = Subdirectory.create! valid_attributes
      expect {
        delete api_v1_directory_subdirectory_url(subdirectory.directory_id, subdirectory.id), headers: valid_headers, as: :json
      }.to change(Subdirectory, :count).by(-1)
    end
  end
end
