version: '3.8'
services:
  db:
    image: postgres:15.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - '.env'
    ports:
      - "5432:3001"
  web:
    build: .
    volumes:
      - .:/test1
    env_file:
      - '.env'
    ports:
      - "3000:3000"
    depends_on:
      - db