default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: default
  password: default
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: ruby_dev_test_1_development

test:
  <<: *default
  database: ruby_dev_test_1_test

production:
  <<: *default
  database: ruby_dev_test_1_production
  username: ruby_dev_test_1
  password: <%= ENV["RUBY_DEV_TEST_1_DATABASE_PASSWORD"] %>
