development:
  adapter: postgresql
  encoding: unicode
  database: morphy_development
  pool: 5
  username: eduardovrocha
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: morphy_test
  pool: 5
  username: eduardovrocha
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: morphy_production
  pool: 5
  username: eduardovrocha
  password: