default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: directories_api_development
  username: api_admin
  password: root

test:
  <<: *default
  database: directories_api_test
  username: api_admin
  password: root