default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: apple_pie_development

test:
  <<: *default
  database: apple_pie_test
