default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rubydev_development
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432

  
production:
  <<: *default
  database: ruby_dev_test_1_production
  username: ruby_dev_test_1
  password: <%= ENV["RUBY_DEV_TEST_1_DATABASE_PASSWORD"] %>
