disk:
  service: Disk
  root: <%= Rails.root.join("#{Rails.env.test? ? 'temp/' : ''}storage") %>

# Use bin/rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
s3:
  service: S3
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %> # AKIAXUBYE7CDDXWH2QPX
  secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %> # 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
  region: <%= ENV['S3_REGION'] %> # sa-east-1
  bucket: <%= ENV['S3_BUCKET'] %> # cadore-clicksign

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket-<%= Rails.env %>

# Use bin/rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name-<%= Rails.env %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
